### ISSUE TITLE
Hangs in large project VS2019

### ISSUE THREAD

**Issue by ArcEarth** [Benio101/Color.Token#1]
I am really happy with the idea about this extension, however, it is right now causing a lot of hang for VS2019 in our source repo. Have to disable this extension.
The hang usually happens in the 'background database update'.

**Comment by Benio101** [comment]
Hey, ArcEarth.

#### Issue
Embarrassingly, I've been publishing `Debug` binaries instead of `Release` ones.

#### Fix
I've fixed that and published correct `Debug` version in 1.1 release, both on Github and Marketplace. Additionally, I've simplified regex matching of Identifier (84d56019d3bcccd17f4ab29cfc0cdb07e98139c5, also in 1.1). It should not trigger full file scan on database update.

#### Help wanted
If you could test if new release works without hang now, it would be appreciated ([Github](https://github.com/Benio101/Color.Token/releases/tag/1.1) · [Marketplace](https://marketplace.visualstudio.com/items?itemName=Benio.ColorToken)).
Otherwise, I'll test it on 2019 once I'll buy a license as my 30 days period of 2019 Preview has expired.

**Comment by ArcEarth** [comment]
I just updated the extension, however, it still cause VS to hang on project open:
![image](https://user-images.githubusercontent.com/2577491/55494731-5870e980-5609-11e9-97a4-e57459f769dc.png)

Trying this with a very small project, but still got a hang:
![image](https://user-images.githubusercontent.com/2577491/55494961-daf9a900-5609-11e9-99a0-13a2fdb52319.png)
![image](https://user-images.githubusercontent.com/2577491/55494989-e6e56b00-5609-11e9-8d0b-25da6127f5c7.png)

**Comment by Benio101** [comment]
Nah, unfortunatelly cannot reproduce on VS2019 neither on small projects nor on big ones, like Unreal Engine 4 project.
