### ISSUE TITLE
Code editor scrolling with delay

### ISSUE THREAD

**Issue by SpriteOvO** [Benio101/Color.Token#10]
# Bug report

Code editor scrolling with delay

#### Expected behavior

Smooth scrolling without delay.

(This GIF recorded when I disabled _Color.Token_)

![1](https://user-images.githubusercontent.com/33660554/93087358-ff94f400-f6ca-11ea-8e30-f6a2f7d78585.gif)

#### Actual behavior

Scrolling with significant delay.

![2](https://user-images.githubusercontent.com/33660554/93087333-fa37a980-f6ca-11ea-9555-8cf7949ddd03.gif)

**Comment by Benio101** [comment]
While I can confirm the issue can be reproduces, this is due to how (poorly imho) code map on scrollbars works, so the issue is not related to my extensions, afaik. Due to this, and yet more issues with code map I don't use this feature btw.
Anyway, I abandon the project, so this extension won't get any more updates from me anyway. Sorry.

**Comment by SpriteOvO** [comment]
It's okay, still thanks for what you did.
