### ISSUE TITLE
Problem when installed w/Supercharger.

### ISSUE THREAD

**Issue by davegi** [Benio101/Color.Token#7]
When both the Color.Token and Supercharger extensions are (the only) enabled extensions in a clean Experimental instance of VS Community 2019; single-stepping hangs VS.

This occurs on a small C++ program and can be reproduced by pressing F11 as fast as possible; VS will eventually become unresponsive. This does not occur without an extensions enabled, or w/only Color.Token or Supercharger enabled.

I've sent the same report to Supercharger (http://supercharger.tools/support.html).

**Comment by Benio101** [comment]
According to marketplace site, [Supercharger](https://marketplace.visualstudio.com/items?itemName=MichaelKissBG8.Supercharger) is not an open source extension, and it's paid for any but Community Edition. This means I would have to pay in order to be able to reproduce a bug. Also, this would not guarantee reproduction since Supercharger extension is not open source. If you could provide a way to reproduce a bug, not behind a paywall, and ability to debug it, feel free to reopen this issue.

**Comment by davegi** [comment]
Your call. I know that Supercharger is super popular so an incompatibility is likely not good. Maybe you can reach out to the Supercharger dev and work w/him. FYI, as best as I can tell, the problem seems to happen only when Supercharger’s Magic Comments are enabled. I’ve told the Supercharger dev about this.
Good luck,
djg
