### ISSUE TITLE
Color Prioritization

### ISSUE THREAD

**Issue by kALLEBALIK** [Benio101/Color.Token#9]
# Improvement request
### Short Description

Love the extension but i have problem with the priority of Color.Token. It seems to be overridden by other color settings; default or others. Is there a way to make sure Color.Token colors is always prioritized?
#### Pros

- More Control.

#### Cons

-

**Comment by Benio101** [comment]
In order to change priority of certain colors, edit `Style.cs` file, and change `Order` attributes ([Style.cs#L13](https://github.com/Benio101/Color.Token/blob/master/Color.Token/Style.cs#L13)).
Since classification, which needs to be put in `Order` is not documented, I won't touch it. Mind using something like [this](https://github.com/Benio101/Color.Misc/blob/master/Color.Misc/Style.cs#L12).
Note I'm no longer working on msvc extensions, including this one. Sorry.
Changing status to `Won't fix` as I abandon the project.
